name: Run Docker Container

# Trigger the workflow only on pull requests to the main branch
on:
  pull_request:
    branches:
      - main

jobs:
  run-docker-container:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code in case you need it
      - name: Checkout code
        uses: actions/checkout@v3

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      # Pull the Docker image
      - name: Pull Docker image
        run: docker pull sd2879/cad_pdf_extractor:latest

      # Run the Docker container
      - name: Run Docker container
        run: docker run -d -p 8888:8888 sd2879/cad_pdf_extractor:latest
